language: node_js
node_js:
  - "0.12"

branches:
  only:
    - master
    - stable
    - test

services:
  - redis-server

before_script:
  - psql -c 'create database crypton_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make
